### ISSUE TITLE
List of issues / suggested chagnes for headlights tracking

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3107]
(Feel free to expand the list or re-order)

#### Must Fix

- [x] command-click on the panel icon send
`user-interface > panels-visible > layersLibrary-visible`
should be
`user-interface > panels-visible > none-visible`

- [x] Mouse over blend mode (layer, shadow, color-overlay, etc.) list result in many event logs. Should only emit the final blend mode.

- [x] Clicking the + icon in the export panel sent
`export > preset > SyntheticMouseEvent`

- [x] Should have events for toggling panel (double-click on panel title)

- [x] I don't see any mask mode tracking, and this seems missing event name? ```headlights.logEvent("tools", "mask-mode-" + currentLayer.kind); ```

- [x] Should track sampler primary (mouse click on layer) and secondary click (mouse click on layer with shift key)

#### If time permitted

- [ ] Should have `fill-activation` for fill colors

- [x] Should track for “export”, “search", and "vector mask" buttons in the headers, and dismiss of search dialog
(I don't see the `tools > search > failed-search` after dismissing the dialog)

- [x] Should have better naming for export configuration.
`export > asset > scale-1-suffix-@1x-setting-png`
maybe
`export > asset > scale-1/suffix-@1x/setting-png`

**Divya's thoughts** The current standard is to separate all words with "-". We should decided on a overarching syntax if we make the above change and then make sure all the other logEvents are consistent with this. 

- [ ] Sending two events if copy layer via shortcut
`menu > EDIT > COPY`
`edit > layers > copy-layers`
Same for pasting layer
`menu > EDIT > PASTE`
`edit > layers > paste-layers`
may be we should get ride of the menu logging for copy/past layer?

**Divya's thoughts** I think we should keep this to see how users navigate to copy/paste because the trail to copy or paste in each case is different.

- [x] Create text layer sent
`tools > create > typeCreateOrEdit`

- [x] Clicking menu command send
`menu > WINDOW > TOGGLE_TOOLBAR`

- [x] Many `_logSuperselect` names are not in kebob case, for example: `click_select`, `select_all`, `marqueeSelect`

- [x] Confirm search sent
`search > filter-inactive > category-ALL_LAYER

- [ ] Copy/Paste style
`headlights: style > create > copy-all-styles`
should have more details
`headlights: style > create > copy-text-styles`
`headlights: style > create > copy-vector-styles`
`headlights: style > create > copy-layer-styles`

- [ ] Click sampler HUD icons send
`tools > sampler-hud > layerEffects`

**Comment by shaoshing** [comment]
- [ ] test more tasks
